# Generated by Django 5.2.5 on 2025-10-21 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tank_capacity_liters', models.PositiveIntegerField(default=1000, help_text='Total capacity of the main user tank in Liters.')),
                ('pump_present', models.BooleanField(default=True, help_text='Set to False if this is a monitor-only device with no pump.')),
                ('overload_current_amps', models.FloatField(default=15.0, help_text='Current threshold for overload detection (Amps)')),
                ('dry_run_current_amps', models.FloatField(default=2.0, help_text='Current threshold for dry run detection (Amps)')),
                ('tank_1_reading_id', models.CharField(blank=True, help_text='Reading ID for Tank 1 (auto-detected from IoT data)', max_length=100, null=True)),
                ('tank_1_name', models.CharField(blank=True, help_text='Name for Tank 1 (enter only if reading_id exists)', max_length=100, null=True)),
                ('tank_1_is_source', models.BooleanField(default=False, help_text='Check if Tank 1 is the source tank (water supply)')),
                ('tank_2_reading_id', models.CharField(blank=True, help_text='Reading ID for Tank 2 (auto-detected from IoT data)', max_length=100, null=True)),
                ('tank_2_name', models.CharField(blank=True, help_text='Name for Tank 2 (enter only if reading_id exists)', max_length=100, null=True)),
                ('tank_2_is_source', models.BooleanField(default=False, help_text='Check if Tank 2 is the source tank (water supply)')),
                ('tank_3_reading_id', models.CharField(blank=True, help_text='Reading ID for Tank 3 (auto-detected from IoT data)', max_length=100, null=True)),
                ('tank_3_name', models.CharField(blank=True, help_text='Name for Tank 3 (enter only if reading_id exists)', max_length=100, null=True)),
                ('tank_3_is_source', models.BooleanField(default=False, help_text='Check if Tank 3 is the source tank (water supply)')),
                ('tank_4_reading_id', models.CharField(blank=True, help_text='Reading ID for Tank 4 (auto-detected from IoT data)', max_length=100, null=True)),
                ('tank_4_name', models.CharField(blank=True, help_text='Name for Tank 4 (enter only if reading_id exists)', max_length=100, null=True)),
                ('tank_4_is_source', models.BooleanField(default=False, help_text='Check if Tank 4 is the source tank (water supply)')),
                ('solenoid_1_reading_id', models.CharField(blank=True, help_text='Reading ID for Solenoid Valve 1 (auto-detected from IoT data)', max_length=100, null=True)),
                ('solenoid_1_name', models.CharField(blank=True, help_text='Name for Solenoid Valve 1 (enter only if reading_id exists)', max_length=100, null=True)),
                ('solenoid_2_reading_id', models.CharField(blank=True, help_text='Reading ID for Solenoid Valve 2 (auto-detected from IoT data)', max_length=100, null=True)),
                ('solenoid_2_name', models.CharField(blank=True, help_text='Name for Solenoid Valve 2 (enter only if reading_id exists)', max_length=100, null=True)),
                ('solenoid_3_reading_id', models.CharField(blank=True, help_text='Reading ID for Solenoid Valve 3 (auto-detected from IoT data)', max_length=100, null=True)),
                ('solenoid_3_name', models.CharField(blank=True, help_text='Name for Solenoid Valve 3 (enter only if reading_id exists)', max_length=100, null=True)),
                ('solenoid_4_reading_id', models.CharField(blank=True, help_text='Reading ID for Solenoid Valve 4 (auto-detected from IoT data)', max_length=100, null=True)),
                ('solenoid_4_name', models.CharField(blank=True, help_text='Name for Solenoid Valve 4 (enter only if reading_id exists)', max_length=100, null=True)),
                ('last_alert_type', models.CharField(blank=True, max_length=50, null=True)),
                ('last_alert_sent_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Rule', max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('monitor_tank_name', models.CharField(blank=True, default='Overhead', help_text="The 'name' of the tank to monitor (e.g., 'Overhead')", max_length=100)),
                ('min_level', models.PositiveIntegerField(default=20, help_text='Pump ON when level is BELOW this %')),
                ('max_level', models.PositiveIntegerField(default=95, help_text='Pump OFF when level is ABOVE this %')),
                ('enabled', models.BooleanField(default=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='dashboard.device')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('fcm_token', models.TextField(blank=True, help_text='Firebase Cloud Messaging token for push notifications', null=True)),
                ('push_notifications_enabled', models.BooleanField(default=True, help_text='Enable/disable push notifications')),
                ('last_notification_sent', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WaterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('system_data', models.JSONField(default=dict)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='dashboard.device')),
            ],
        ),
        migrations.CreateModel(
            name='DailyWaterUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_user_water_liters', models.FloatField(default=0.0)),
                ('total_stored_water_liters', models.FloatField(default=0.0)),
                ('total_power_kwh', models.FloatField(default=0.0)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_usage', to='dashboard.device')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('device', 'date')},
            },
        ),
    ]
