# Generated by Django 5.2.5 on 2025-08-07 05:46
# In the new file, e.g., dashboard/migrations/0002_auto_....py
from django.db import migrations
import os

def create_superuser(apps, schema_editor):
    # We get the User model
    User = apps.get_model('auth', 'User')
    
    # We read the admin credentials from secure environment variables
    ADMIN_USERNAME = os.environ.get('ADMIN_USERNAME')
    ADMIN_PASSWORD = os.environ.get('ADMIN_PASSWORD')
    ADMIN_EMAIL = os.environ.get('ADMIN_EMAIL', 'admin@example.com')

    # We only create the user if the variables are set and the user doesn't already exist
    if ADMIN_USERNAME and ADMIN_PASSWORD:
        if not User.objects.filter(username=ADMIN_USERNAME).exists():
            print(f"Creating superuser: {ADMIN_USERNAME}")
            User.objects.create_superuser(
                username=ADMIN_USERNAME,
                email=ADMIN_EMAIL,
                password=ADMIN_PASSWORD
            )
        else:
            print(f"Superuser '{ADMIN_USERNAME}' already exists.")

class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'), # This should match your first migration file
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]