# Generated by Django 5.2.7 on 2025-10-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='tank_1_capacity_liters',
            field=models.PositiveIntegerField(default=1000, help_text='Capacity of Tank 1 in Liters'),
        ),
        migrations.AddField(
            model_name='device',
            name='tank_2_capacity_liters',
            field=models.PositiveIntegerField(default=1000, help_text='Capacity of Tank 2 in Liters'),
        ),
        migrations.AddField(
            model_name='device',
            name='tank_3_capacity_liters',
            field=models.PositiveIntegerField(default=1000, help_text='Capacity of Tank 3 in Liters'),
        ),
        migrations.AddField(
            model_name='device',
            name='tank_4_capacity_liters',
            field=models.PositiveIntegerField(default=1000, help_text='Capacity of Tank 4 in Liters'),
        ),
    ]
