# Generated by Django 5.2.5 on 2025-10-16 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_device_last_alert_sent_at_device_last_alert_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waterreading',
            old_name='pump_current',
            new_name='pump_current_amps',
        ),
        migrations.AddField(
            model_name='dailywaterusage',
            name='pump_runtime_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dailywaterusage',
            name='total_power_kwh',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dailywaterusage',
            name='total_stored_liters',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='waterreading',
            name='pump_mode',
            field=models.CharField(default='AUTO', max_length=50),
        ),
        migrations.AddField(
            model_name='waterreading',
            name='tank_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='waterreading',
            name='overhead_level',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='waterreading',
            name='pump_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='waterreading',
            name='system_status',
            field=models.CharField(default='OK', max_length=100),
        ),
        migrations.AlterField(
            model_name='waterreading',
            name='underground_level',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Night Time Pumping'", max_length=100)),
                ('start_time', models.TimeField(help_text='When this rule becomes active')),
                ('end_time', models.TimeField(help_text='When this rule becomes inactive')),
                ('min_level', models.IntegerField(help_text='Pump ON when destination tank reaches this level (%)')),
                ('max_level', models.IntegerField(help_text='Pump OFF when destination tank reaches this level (%)')),
                ('destination_tank', models.CharField(default='Overhead', help_text='Which tank to monitor', max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='dashboard.device')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
