# Generated by Django 5.2.7 on 2025-10-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_device_tank_1_capacity_liters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='tank_1_capacity_liters',
            field=models.PositiveIntegerField(blank=True, default=500, help_text='Capacity of Tank 1 in liters', null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='tank_2_capacity_liters',
            field=models.PositiveIntegerField(blank=True, default=500, help_text='Capacity of Tank 2 in liters', null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='tank_3_capacity_liters',
            field=models.PositiveIntegerField(blank=True, default=500, help_text='Capacity of Tank 3 in liters', null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='tank_4_capacity_liters',
            field=models.PositiveIntegerField(blank=True, default=500, help_text='Capacity of Tank 4 in liters', null=True),
        ),
    ]
