# Generated by Django 5.2.7 on 2025-10-23 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_device_tank_1_capacity_liters_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailywaterusage',
            options={'ordering': ['-date'], 'verbose_name': 'Usage', 'verbose_name_plural': 'Usage'},
        ),
    ]
