# Generated by Django 5.2.5 on 2025-10-17 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_pump_current_waterreading_pump_current_amps_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automationrule',
            options={},
        ),
        migrations.AlterModelOptions(
            name='dailywaterusage',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveIndex(
            model_name='dailywaterusage',
            name='dashboard_d_day_77c449_idx',
        ),
        migrations.RenameField(
            model_name='dailywaterusage',
            old_name='day',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='dailywaterusage',
            old_name='pump_runtime_hours',
            new_name='total_stored_water_liters',
        ),
        migrations.RemoveField(
            model_name='automationrule',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='automationrule',
            name='destination_tank',
        ),
        migrations.AlterUniqueTogether(
            name='dailywaterusage',
            unique_together={('device', 'date')},
        ),
        migrations.RemoveField(
            model_name='waterreading',
            name='overhead_level',
        ),
        migrations.RemoveField(
            model_name='waterreading',
            name='pump_mode',
        ),
        migrations.RemoveField(
            model_name='waterreading',
            name='system_status',
        ),
        migrations.RemoveField(
            model_name='waterreading',
            name='underground_level',
        ),
        migrations.AddField(
            model_name='automationrule',
            name='monitor_tank_name',
            field=models.CharField(blank=True, default='Overhead', help_text="The 'name' of the tank to monitor (e.g., 'Overhead')", max_length=100),
        ),
        migrations.AddField(
            model_name='dailywaterusage',
            name='total_user_water_liters',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='device',
            name='pump_present',
            field=models.BooleanField(default=True, help_text='Set to False if this is a monitor-only device with no pump.'),
        ),
        migrations.AddField(
            model_name='device',
            name='tank_capacity_liters',
            field=models.PositiveIntegerField(default=1000, help_text='Total capacity of the main user tank in Liters.'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='dashboard.device'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='max_level',
            field=models.PositiveIntegerField(default=95, help_text='Pump OFF when level is ABOVE this %'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='min_level',
            field=models.PositiveIntegerField(default=20, help_text='Pump ON when level is BELOW this %'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='name',
            field=models.CharField(default='My Rule', max_length=100),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='waterreading',
            name='tank_data',
            field=models.JSONField(default=list),
        ),
        migrations.RemoveField(
            model_name='dailywaterusage',
            name='total_stored_liters',
        ),
        migrations.RemoveField(
            model_name='dailywaterusage',
            name='total_usage_liters',
        ),
    ]
