# Generated by Django 5.2.7 on 2025-10-23 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_dailywaterusage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailywaterusage',
            name='total_pump_runtime_hours',
            field=models.FloatField(default=0.0),
        ),
    ]
