# Generated by Django 5.2.7 on 2025-10-23 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_dailywaterusage_total_pump_runtime_hours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FCMToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(help_text='Firebase Cloud Messaging token')),
                ('device_type', models.CharField(default='web', help_text='Device type (web, mobile, etc.)', max_length=50)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this token is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_used'],
                'unique_together': {('user', 'token')},
            },
        ),
    ]
