# Generated by Django 5.2.7 on 2025-10-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_profile_special_user_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='special_user_number',
            field=models.CharField(blank=True, help_text='4-digit special user number for easy identification', max_length=10, null=True, unique=True),
        ),
    ]
