# Generated by Django 5.2.7 on 2025-10-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_profile_special_user_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcmtoken',
            name='user_special_id',
            field=models.CharField(blank=True, help_text="User's special number for easy lookup", max_length=10),
        ),
    ]
