# Generated by Django 5.2.7 on 2025-10-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_fcmtoken_user_special_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceFCMToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, help_text='Unique device identifier (UUID or browser fingerprint)', max_length=255)),
                ('fcm_token', models.TextField(db_index=True, help_text='Firebase Cloud Messaging token', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Device FCM Token',
                'verbose_name_plural': 'Device FCM Tokens',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='FCMToken',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
