# Generated by Django 5.2.5 on 2025-10-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_add_source_tank_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='tank_1_name',
            field=models.CharField(blank=True, help_text='Name for Tank 1 (enter only if reading_id exists)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='tank_2_name',
            field=models.CharField(blank=True, help_text='Name for Tank 2 (enter only if reading_id exists)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='tank_3_name',
            field=models.CharField(blank=True, help_text='Name for Tank 3 (enter only if reading_id exists)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='tank_4_name',
            field=models.CharField(blank=True, help_text='Name for Tank 4 (enter only if reading_id exists)', max_length=100, null=True),
        ),
    ]
