# Generated by Django 5.2.7 on 2025-10-26 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_devicefcmtoken_remove_profile_user_delete_fcmtoken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailywaterusage',
            name='peak_hours',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
